### ISSUE TITLE
Allow multi select during import packs

### ISSUE THREAD

**Issue by borisrorsvort** [olup/lunii-admin#10]
it’s really painful to upload 3rd party packs one by one, allowing multi select during import dialog and then chain import would be such a time saver! 

🙏 thank for the work done already, very sleak ❤️

**Comment by olup** [comment]
Good idea 👍. Let's see if I can get some time to add this feature. Or if you feel like making a PR :-)

**Comment by olup** [comment]
Is the lastest next version a good enough experience ? I just hacked it through so maybe a bit raw. Let me know

**Comment by borisrorsvort** [comment]
@olup works great! I guess that at some point you’d want info on a specific pack failure if that occurs and in that case:
- don’t abort other tasks
- add some clear error message to spécifie which one failed

**Comment by borisrorsvort** [comment]
Spoke too fast ^^ Tried to upload 5 at once and:
<img width="736" alt="Capture d’écran 2023-06-03 à 22 46 22" src="https://github.com/olup/lunii-admin/assets/39081/624e8fca-def9-47df-8390-6adae08fdd49">

Also I dunno what’s happening if the disk is full? Maybe some indicator and failsafe to avoid having full disk errors?

**Comment by olup** [comment]
What happened in your screenshot ?

**Comment by borisrorsvort** [comment]
@olup that’s when you run the multiple import. Running on a Mac book pro.
<img width="215" alt="Capture d’écran 2023-06-05 à 15 21 22" src="https://github.com/olup/lunii-admin/assets/39081/2fc20e46-8e32-44e3-9f83-578883c9ed0b">
